sonar.projectKey=java:data-ingestion-feedback-layer
sonar.projectName=data-ingestion-feedback-layer
sonar.projectBaseDir=data-ingestion/feedback-layer
sonar.sources=src
# Modules inherit properties set at parent level
sonar.sourceEncoding=UTF-8
sonar.language=java
sonar.java.source=11
sonar.java.binaries=target/classes
sonar.java.libraries=target/*.jar
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml,
# Exclude unit tests
sonar.exclusions=**/configuration/*.java,**/properties/*.java,**/target/**/*,**/src/test/**/*
sonar.coverage.exclusions=**/configuration/*.java,**/properties/*.java,**/target/**/*,**/src/test/**/*
